---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-deployment-name
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: scf
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-system-domain
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: fissile.dev
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-locket-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${locket_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-uaa-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${uaa_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-cc-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cc_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-diego-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${diego_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-routing-api-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${routing_api_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-icd-pg-cert
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  certificate: ${icd_pg_cert}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-icd-pg-host
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: ${icd_pg_host}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-icd-pg-port
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: ${icd_pg_port}
