---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-locket-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${locket_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-uaa-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${uaa_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-cc-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cc_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-diego-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${diego_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-routing-api-database-password
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${routing_api_database_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-icd-pg-cert
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  certificate: ${icd_pg_cert}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-icd-pg-host
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: ${icd_pg_host}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-icd-pg-port
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: '${icd_pg_port}'
