---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-blobstore-endpoint
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: ${cos_endpoint}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-blobstore-access-key
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cos_access_key}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-blobstore-secret-key
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cos_secret_key}
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-bucket-resources
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: scf-resources
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-bucket-buildpacks
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: scf-buildpacks
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-bucket-droplet
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: scf-droplet
---
apiVersion: v1
kind: Secret
metadata:
  name: scf.var-bucket-apps
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: scf-apps
