---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-blobstore-endpoint
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: ${cos_endpoints}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-blobstore-access-key
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cos_hmac_keys.access_key_id}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-blobstore-secret-key
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  password: ${cos_hmac_keys.secret_access_key}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-bucket-resources
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: kubecf-resources
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-bucket-buildpacks
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: kubecf-buildpacks
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-bucket-droplet
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: kubecf-droplet
---
apiVersion: v1
kind: Secret
metadata:
  name: kubecf.var-bucket-apps
  labels:
    app.kubernetes.io/managed-by: user
stringData:
  value: kubecf-apps
